### ISSUE TITLE
github操作问题

### ISSUE THREAD

**Issue by yuanrui** [gotgit/gotgit#52]
请问Fork了别人一个分支代码库了后，怎么样与原始的版本库同步。eg.很久以前我fork了The-Art-Of-Programming-By-July这个项目，现在想将主版本同步到我的分支版本呢。谢谢！

**Comment by fanhongwei** [comment]
从主仓库fetch一下  然后合到你分支里边来就好

-- 
Dsnc
Sent with Airmail

On March 18, 2015 at 10:56:05 PM, yuanrui (notifications@github.com) wrote:

请问Fork了别人一个分支代码库了后，怎么样与原始的版本库同步。eg.很久以前我fork了The-Art-Of-Programming-By-July这个项目，现在想将主版本同步到我的分支版本呢。谢谢！

**Comment by yuanrui** [comment]
嗯 对git不太懂，能具体说明下在github的主仓库页面中如何操作么？ 没有在页面中找到如何fetch的操作。
![2](https://cloud.githubusercontent.com/assets/3859838/6764779/e533d130-cffc-11e4-90d8-4406c7c303ed.png)

**Comment by yuanrui** [comment]
还我自己来 回答吧 
步骤1、单击 New pull request,  创建一个新的合并请求
步骤2、交换合并请求 
详细操作交换前 界面是这样子的:
![qq 20150910171925](https://cloud.githubusercontent.com/assets/3859838/9784822/65292410-57e0-11e5-9763-a6d105dc2205.png)
交换后
![qq 2](https://cloud.githubusercontent.com/assets/3859838/9784840/813cb2d4-57e0-11e5-9e1d-4ce685f6a968.png)
步骤3、单击 Create pull request 进行合并，填写注释后提交
步骤4、确认 生效

**Comment by yuanrui** [comment]
问题得到解决 关闭
